require("config.options")
require("config.keymaps")

require("plugins.core")
require("plugins.colorscheme")
require("plugins.noice")
require("plugins.statusline")
require("plugins.gitsigns")
require("plugins.which-key")
require("plugins.blink")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.neo-tree")
require("plugins.mason")
