require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.core")
require("plugins.which-key")
require("plugins.blink")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.conform")