vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.smarttab = true
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.breakindent = true
vim.o.number = true
vim.o.relativenumber = false
vim.o.signcolumn = "yes"
vim.o.mouse = "a"
vim.o.showmode = false
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.clipboard = "unnamedplus"
